import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, ReferenceLine } from 'recharts'

export default function LongitudinalAnalysis({ data }: { data: any }) {
  // Extracting keys (Student_1, Student_2, etc.) dynamically
  const students = Object.keys(data.longitudinal[0]).filter(k => k !== 'week')

  return (
    <div className="space-y-6">
      <div className="border-b border-slate-200 pb-4">
        <h2 className="text-2xl font-semibold text-slate-900 tracking-tight">Longitudinal Distress Analysis</h2>
        <p className="text-slate-500 mt-1">8-week temporal trend evaluation triggering consent-gated interventions.</p>
      </div>

      <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
        <div className="flex justify-between items-start mb-6">
          <div>
            <h3 className="text-sm font-bold uppercase tracking-wider text-slate-800">Weekly Sentiment Moving Averages</h3>
            <p className="text-xs text-slate-500 mt-1">Source: Synthetic cohort generated by longitudinal.py</p>
          </div>
          <div className="text-right">
            <span className="inline-block px-3 py-1 bg-red-100 text-red-700 text-xs font-bold rounded-full border border-red-200">
              Escalation Triggered: Student_1, Student_2
            </span>
          </div>
        </div>

        <div className="h-96">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={data.longitudinal} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
              <XAxis dataKey="week" tick={{fontSize: 12}} tickLine={false} axisLine={false} tickFormatter={(val) => `Week ${val}`} />
              <YAxis domain={[0, 1]} tick={{fontSize: 12}} tickLine={false} axisLine={false} label={{ value: 'Sentiment Score (1=Positive, 0=Distress)', angle: -90, position: 'insideLeft', style: {textAnchor: 'middle', fill: '#64748b', fontSize: 12} }} />
              <Tooltip 
                contentStyle={{borderRadius: '8px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)'}}
              />
              <Legend wrapperStyle={{fontSize: '12px', paddingTop: '20px'}} />
              
              {/* Threshold line */}
              <ReferenceLine y={0.5} stroke="#ef4444" strokeDasharray="3 3" label={{ position: 'right', value: 'Intervention Threshold', fill: '#ef4444', fontSize: 12, fontWeight: 600 }} />

              {students.map((student) => {
                const isTriggered = student === 'Student_1' || student === 'Student_2'
                return (
                  <Line 
                    key={student}
                    type="monotone" 
                    dataKey={student} 
                    stroke={isTriggered ? (student === 'Student_1' ? '#ef4444' : '#f97316') : '#94a3b8'} 
                    strokeWidth={isTriggered ? 3 : 1} 
                    dot={{r: isTriggered ? 4 : 2, fill: isTriggered ? (student === 'Student_1' ? '#ef4444' : '#f97316') : '#94a3b8'}} 
                    opacity={isTriggered ? 1 : 0.6}
                  />
                )
              })}
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>
    </div>
  )
}
